In [1]:
# Imports
import pandas as pd

In [2]:
# Load data from master file
source_csv = # set path
source_df = pd.read_pickle(source_csv)
print(source_df.columns)

Index(['Row_id', 'CONS_question', 'CONS_answer', 'CONS_alt answers',
       'CONS_category', 'CONS_alt categories - NOT USED',
       'CONS_type-formulation', 'CONS_type-multipleChoice', 'ORIG_question',
       'ORIG_answer', 'ORIG_alt answers', 'ORIG_category',
       'ORIG_alt categories', 'ORIG_difficulty', 'ORIG_type', 'namedEntities',
       'nouns', 'objects', 'subjects', 'nounsObjectsSubjects', 'searchTerms',
       'wikipediaSearchSuccessful', 'findQuestionCategories_meta',
       'wikipediaArticleTitle', 'wikipediaArticleID', 'categoryPath',
       'parentCategories', 'searchTermUsed_idx', 'searchTermUsed',
       'WikipediaHighestCat', 'categoryPathList', 'WikiCat_0', 'WikiCat_1',
       'WikiCat_2', 'WikiCat_3', 'WikiCat_4', 'WikiCat_5', 'WikiCat_6',
       'WikiCat_7', 'WikiCat_8', 'WikiCat_9', 'WikiCat_10', 'WikiCat_11',
       'WikiCat_12', 'WikiCat_13', 'WikiCat_14', 'WikiCat_15', 'WikiCat_16',
       'WikiPath_Category', 'WikiPath_Exceptions', 'WikiPath_withExceptions',
       'hasHistoryNumber', 'searchTermCatExceptions', 'Master_category',
       'Language', 'primarySet'],
      dtype='object')

In [3]:
# Keep only rows where primarySet == True
full_df = source_df.loc[source_df["primarySet"] == True]

In [4]:
full_df

,Row_id,CONS_question,CONS_answer,CONS_alt answers,CONS_category,CONS_alt categories - NOT USED,CONS_type-formulation,CONS_type-multipleChoice,ORIG_question,ORIG_answer,...,WikiCat_15,WikiCat_16,WikiPath_Category,WikiPath_Exceptions,WikiPath_withExceptions,hasHistoryNumber,searchTermCatExceptions,Master_category,Language,primarySet
0,0,"""Now is the winter of our discontent"" is a lin...",Richard III,"[Romeo and Juliet, Macbeth]",Art and literature,NaN,Question,True,"""Now is the winter of our discontent"" is a lin...",0,...,None,None,Entertainment and games,Art and literature,Art and literature,False,None,Art and literature,en,True
1,1,"""Our Town"" is a play by whom?",Thornton Wilder,NaN,Art and literature,NaN,Question,False,"""Our Town"" is a play by whom?",0,...,None,None,Entertainment and games,Art and literature,Art and literature,False,None,Art and literature,en,True
2,2,"""The Diary of Anne Frank"" was first published ...",The diary of a young girl,NaN,Art and literature,NaN,Question,False,"""The Diary of Anne Frank"" was first published ...",0,...,None,None,Art and literature,,Art and literature,False,None,Art and literature,en,True
3,3,"A band of painted or sculpted decoration, ofte...",A frieze,NaN,Art and literature,NaN,Statement - open,False,"A band of painted or sculpted decoration, ofte...",0,...,None,None,Art and literature,,Art and literature,False,None,Art and literature,en,True
4,4,A composition made of cut and pasted pieces of...,Collage,NaN,Art and literature,NaN,Statement - open,False,A composition made of cut and pasted pieces of...,0,...,None,None,History and society,,History and society,False,None,Art and literature,en,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64534,64534,What was the original intended use for the RC ...,War,NaN,Uncategorized,NaN,Question,False,What was the original intended use for the RC ...,War,...,None,None,Entertainment and games,,Entertainment and games,False,None,Entertainment and games,en,True
64535,64535,What was the name of the sacred river in Samue...,Alph,NaN,Art and literature,NaN,Question,False,What was the name of the sacred river in Samue...,Alph,...,None,None,Art and literature,,Art and literature,False,None,Art and literature,en,True
64536,64536,Who played James Bond in Diamonds Are Forever?,Sean Connery,NaN,Entertainment and games,NaN,Question,False,Who played James Bond in Diamonds Are Forever?,Sean Connery,...,None,None,Entertainment and games,Art and literature,Art and literature,False,None,Entertainment and games,en,True
64537,64537,Who is known as Slim Shady?,Marshall Mathers,NaN,Entertainment and games,NaN,Question,False,Who is known as Slim Shady?,Marshall Mathers,...,None,None,Entertainment and games,,Entertainment and games,False,None,Entertainment and games,en,True
64538,64538,What is the name of King Arthur's sidekick in ...,Patsy,NaN,Entertainment and games,NaN,Question,False,What is the name of King Arthur's sidekick in ...,Patsy,...,None,None,Entertainment and games,,Entertainment and games,False,None,Entertainment and games,en,True

In [5]:
# Keep only rows Row_id, CONS_question, CONS_answer, Master_category, Language
columns_to_drop = ['CONS_alt answers', 'CONS_category', 'CONS_alt categories - NOT USED', 'CONS_type-formulation', 'CONS_type-multipleChoice', 'ORIG_question', 'ORIG_answer', 'ORIG_alt answers', 'ORIG_category', 'ORIG_alt categories', 'ORIG_difficulty', 'ORIG_type', 'namedEntities', 'nouns', 'objects', 'subjects', 'nounsObjectsSubjects', 'searchTerms', 'wikipediaSearchSuccessful', 'findQuestionCategories_meta', 'wikipediaArticleTitle', 'wikipediaArticleID', 'categoryPath', 'parentCategories', 'searchTermUsed_idx', 'searchTermUsed', 'WikipediaHighestCat', 'categoryPathList', 'WikiCat_0', 'WikiCat_1', 'WikiCat_2', 'WikiCat_3', 'WikiCat_4', 'WikiCat_5', 'WikiCat_6', 'WikiCat_7', 'WikiCat_8', 'WikiCat_9', 'WikiCat_10', 'WikiCat_11', 'WikiCat_12', 'WikiCat_13', 'WikiCat_14', 'WikiCat_15', 'WikiCat_16', 'WikiPath_Category', 'WikiPath_Exceptions', 'WikiPath_withExceptions', 'hasHistoryNumber', 'searchTermCatExceptions', 'primarySet']
full_df.drop(columns=columns_to_drop, inplace = True)

C:\Users\Fredi\miniconda3\envs\firestore-operations\lib\site-packages\pandas\core\frame.py:4167: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [6]:
# Set column headings
full_df.columns = ['row_id', 'question', 'answer', 'category', 'language']

In [7]:
full_df

,row_id,question,answer,category,language
0,0,"""Now is the winter of our discontent"" is a lin...",Richard III,Art and literature,en
1,1,"""Our Town"" is a play by whom?",Thornton Wilder,Art and literature,en
2,2,"""The Diary of Anne Frank"" was first published ...",The diary of a young girl,Art and literature,en
3,3,"A band of painted or sculpted decoration, ofte...",A frieze,Art and literature,en
4,4,A composition made of cut and pasted pieces of...,Collage,Art and literature,en
...,...,...,...,...,...
64534,64534,What was the original intended use for the RC ...,War,Entertainment and games,en
64535,64535,What was the name of the sacred river in Samue...,Alph,Art and literature,en
64536,64536,Who played James Bond in Diamonds Are Forever?,Sean Connery,Entertainment and games,en
64537,64537,Who is known as Slim Shady?,Marshall Mathers,Entertainment and games,en
64538,64538,What is the name of King Arthur's sidekick in ...,Patsy,Entertainment and games,en

In [8]:
# Remove potential formatting errors
full_df["question"] = full_df["question"].apply(lambda x: x.replace("â€™", "'"))

<ipython-input-8-376655cfa242>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_df["question"] = full_df["question"].apply(lambda x: x.replace("â€™", "'"))

In [9]:
full_df

,row_id,question,answer,category,language
0,0,"""Now is the winter of our discontent"" is a lin...",Richard III,Art and literature,en
1,1,"""Our Town"" is a play by whom?",Thornton Wilder,Art and literature,en
2,2,"""The Diary of Anne Frank"" was first published ...",The diary of a young girl,Art and literature,en
3,3,"A band of painted or sculpted decoration, ofte...",A frieze,Art and literature,en
4,4,A composition made of cut and pasted pieces of...,Collage,Art and literature,en
...,...,...,...,...,...
64534,64534,What was the original intended use for the RC ...,War,Entertainment and games,en
64535,64535,What was the name of the sacred river in Samue...,Alph,Art and literature,en
64536,64536,Who played James Bond in Diamonds Are Forever?,Sean Connery,Entertainment and games,en
64537,64537,Who is known as Slim Shady?,Marshall Mathers,Entertainment and games,en
64538,64538,What is the name of King Arthur's sidekick in ...,Patsy,Entertainment and games,en

In [10]:
full_df.to_csv ("../data/master_import.csv", index = False, header=True)